# Generated by Django 5.1.4 on 2026-03-22 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Назва зони")),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Вартість доставки, ₴",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Мінімальна сума замовлення, ₴",
                    ),
                ),
                (
                    "polygon",
                    models.JSONField(
                        help_text="GeoJSON Polygon coordinates",
                        verbose_name="Полігон (GeoJSON)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1a4a1a",
                        help_text="HEX колір для відображення на карті",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$",
                                "Введіть коректний HEX колір, наприклад #1a4a1a",
                            )
                        ],
                        verbose_name="Колір на карті",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона доставки",
                "verbose_name_plural": "Зони доставки",
                "ordering": ["name"],
            },
        ),
    ]
