# Generated by Django 5.1.4 on 2026-03-22 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="Ключ сесії"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ім'я")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("delivery", "Доставка"), ("pickup", "Самовивіз")],
                        max_length=10,
                        verbose_name="Тип доставки",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адреса")),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Готівка"), ("monobank", "Monobank")],
                        max_length=10,
                        verbose_name="Спосіб оплати",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нове"),
                            ("confirmed", "Підтверджено"),
                            ("delivering", "Доставляється"),
                            ("done", "Виконано"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="new",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сума замовлення"
                    ),
                ),
                (
                    "delivery_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Вартість доставки",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Коментар")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="delivery.deliveryzone",
                        verbose_name="Зона доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Замовлення",
                "verbose_name_plural": "Замовлення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Кількість"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Замовлення",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиція замовлення",
                "verbose_name_plural": "Позиції замовлення",
            },
        ),
    ]
