# Generated by Django 5.1.4 on 2026-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
        migrations.AddField(
            model_name="order",
            name="monobank_invoice_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Monobank Invoice ID"
            ),
        ),
    ]
