# Generated by Django 5.1.4 on 2026-03-22 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_is_paid_order_monobank_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="monobank_invoice_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="Monobank Invoice ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введіть коректний номер телефону у форматі +380XXXXXXXXX або 0XXXXXXXXX",
                        regex="^(\\+380|380|0)\\d{9}$",
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
    ]
