# Generated by Django 5.1.4 on 2026-03-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=300, unique=True, verbose_name="Slug"),
                ),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Відображається в списку статей та в meta description",
                        max_length=500,
                        verbose_name="Короткий опис",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="HTML content", verbose_name="Контент"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="blog/", verbose_name="Зображення"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        default="Heizenberg Ice", max_length=200, verbose_name="Автор"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубліковано"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публікації"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Стаття",
                "verbose_name_plural": "Статті",
                "ordering": ["-published_at"],
            },
        ),
    ]
