# Generated by Django 5.1.4 on 2026-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ім'я")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("message", models.TextField(verbose_name="Повідомлення")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
            ],
            options={
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Питання")),
                ("answer", models.TextField(verbose_name="Відповідь")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
            ],
            options={
                "verbose_name": "Питання та відповідь",
                "verbose_name_plural": "Питання та відповіді",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PageSEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_slug",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Slug сторінки"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="seo/", verbose_name="OG Image"
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO сторінки",
                "verbose_name_plural": "SEO сторінок",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_pickup", models.TextField(verbose_name="Адреса самовивозу")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram URL"),
                ),
                (
                    "monobank_link",
                    models.URLField(blank=True, verbose_name="Посилання Monobank"),
                ),
                (
                    "working_hours",
                    models.CharField(max_length=200, verbose_name="Графік роботи"),
                ),
            ],
            options={
                "verbose_name": "Налаштування сайту",
                "verbose_name_plural": "Налаштування сайту",
            },
        ),
    ]
