# Generated by Django 5.1.4 on 2026-03-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="monobank_link",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="monobank_token",
            field=models.CharField(
                blank=True,
                help_text="Токен мерчанта з https://api.monobank.ua/ (тестовий) або кабінету ФОП (бойовий)",
                max_length=200,
                verbose_name="Monobank токен",
            ),
        ),
    ]
