# Generated by Django 5.1.4 on 2026-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="products/", verbose_name="Зображення"
            ),
        ),
    ]
